### ISSUE TITLE
dependency on logging causing installation errors

### ISSUE THREAD

**Issue by patsfan0199** [zlaski/certbot-dns-zoneedit#5]
This is a great little tool/package.  Thank you for putting it together.

Just a quick note that I ran into pip install error because logging can not be installed properly -- this is on linux using conda for python 3.11.4 environment.  Please see below for the error details -- my understanding, in case it may be helpful, is that since about python 3.8, logging has been absorbed into standard module set instead of being a stand-alone package.

Thanks!

$ pip install certbot-dns-zoneedit
Collecting certbot-dns-zoneedit
  Using cached certbot_dns_zoneedit-0.3.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: acme>=2.4.0 in /home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages (from certbot-dns-zoneedit) (2.7.4)
Requirement already satisfied: certbot>=2.4.0 in /home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages (from certbot-dns-zoneedit) (2.7.4)
Requirement already satisfied: dnspython>=2.3.0 in /home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages (from certbot-dns-zoneedit) (2.4.2)
Collecting logging>=0.4.9 (from certbot-dns-zoneedit)
  Using cached logging-0.4.9.6.tar.gz (96 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages/setuptools/__init__.py", line 7, in <module>
          import _distutils_hack.override  # noqa: F401
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "/home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 63, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 22, in <module>
          from .dist import Distribution
        File "/home/lshu/miniconda3/envs/letsencrypt/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 12, in <module>
          import logging
        File "/tmp/pip-install-61rgrl1i/logging_7afd5982784e47e28eaeebfd30d13642/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dluyer** [comment]
As a workaround, installed on Debian via:

```
# python3 -m venv /home/$USER/python3-venv-certbot-dns-zoneedit
# /home/$USER/python3-venv-certbot-dns-zoneedit/pip3 install certbot-dns-zoneedit
   --> failed at installing logging, but installed most packages
# /home/$USER/python3-venv-certbot-dns-zoneedit/pip3 install --no-deps certbot-dns-zoneedit
# /home/$USER/python3-venv-certbot-dns-zoneedit/pip3 install certbot
   --> pip3 install rust, install a ton of unnecessary stuff, realize this was a mistake
   --> apt install rustc pkg-config librust-openssl-sys-dev ... and retry
# /home/$USER/python3-venv-certbot-dns-zoneedit/pip3 install dnspython
# /home/$USER/python3-venv-certbot-dns-zoneedit/bin/certbot ...
```

**Comment by jameskirsop** [comment]
@zlaski, are you still maintaining this project?

If not, could one of the people in this thread be given access so we can resolve this dependency issue?

**Comment by zlaski** [comment]
I must have misconfigured something somewhere, since I'm not getting automated emails whenever an issue or pull request appears.  Please bear with me. :-(

**Comment by KLelong** [comment]
Hi,
Is this resolved ?
I'm asking because I get the same errors when I try to install the software.
I did try the workaround and eventually I got it to work, but I would like to just install it with pip.

**Comment by maxfieb** [comment]
I got this recently on rocky linux 10, the old python 2.x module caused a failure certbot loading the plugin. 

certbot-dns-zoneedit
    └── Requires: logging>=0.4.9

Had to uninstall the 2.x logging module (python3 -m pip uninstall logging), could be the change has not propagated to Rocky 10.

Also of note, rocky linux 10 (perhaps others) certbot now runs with "python3 -sP", that disables use of non-system paths for python modules, which is where pip installs them (/usr/local). This might be more of a gotcha, as the additional certbot plugins are not trusted system packages, and the path pip uses in the (now?) untrusted /usr/local prefix.

But pip installed modules are a bit of a gotcha ATM, as they are not trusted by default, without adding something like :

PYTHONPATH=/usr/local/lib/python3.12/site-packages

(to any shell you initialise/test with, and the Environment=xx in  certbot's systemd service for timer based renewals)
